### ISSUE TITLE
Document how to create styles

### ISSUE THREAD

**Issue by devsideal** [IO-Design-Team/firebase_ui_oauth_oidc#3]
I'm using code from sample but this class `ExampleButtonStyle` not found, give me error.

```
OidcSignInButton(
      providerId: 'oidc.example',
      style:  const ExampleButtonStyle(), // This line showing error
      loadingIndicator: const CircularProgressIndicator(),
      onSignedIn: (credential) {
      // perform navigation.
     },
),
```

How to set style for `OidcSignInButton`  ?

**Comment by Rexios80** [comment]
This definitely needs added to the readme, but you can check the oauth ui implementations such as [firebase_ui_oauth_google](https://github.com/firebase/flutterfire/blob/master/packages/firebase_ui_oauth_google/lib/src/theme.dart), [firebase_ui_oauth_apple](https://github.com/firebase/flutterfire/blob/master/packages/firebase_ui_oauth_apple/lib/src/theme.dart), etc. for help

**Comment by devsideal** [comment]
Thanks, @Rexios80  by your hint i resolved the buton style error.
But when click on the button, getting this error:
`LateInitializationError: Field 'authListener' has not been initialized.`

**Comment by Rexios80** [comment]
Are your dependencies up to date? That error isn't related to any code in this package.

**Comment by devsideal** [comment]
I'm using this version of dependency: `firebase_ui_oauth_oidc: ^0.2.1`

When I click on the button, the complete log is:

```
======== Exception caught by gesture ===============================================
The following LateError was thrown while handling a gesture:
LateInitializationError: Field 'authListener' has not been initialized.

When the exception was thrown, this was the stack: 
#0      OAuthProvider.authListener (package:firebase_ui_oauth/src/oauth_provider.dart)
#1      OAuthProvider.signIn (package:firebase_ui_oauth/src/oauth_provider.dart:33:5)
#2      _OAuthProviderButtonBaseState._signIn (package:firebase_ui_oauth/src/oauth_provider_button_base.dart:162:16)
#3      _OAuthProviderButtonBaseState._buildMaterial.<anonymous closure> (package:firebase_ui_oauth/src/oauth_provider_button_base.dart:246:44)
#4      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1154:21)
#5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275:24)
#6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:654:11)
#7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:311:5)
#8      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:281:7)
#9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:167:27)
#10     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:469:20)
#11     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:445:22)
#12     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:331:11)
#13     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:400:7)
#14     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:363:5)
#15     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:320:7)
#16     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:293:9)
#17     _invoke1 (dart:ui/hooks.dart:158:13)
#18     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:382:7)
#19     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:31)
Handler: "onTap"
Recognizer: TapGestureRecognizer#3ec88
  debugOwner: GestureDetector
  state: ready
  won arena
  finalPosition: Offset(162.7, 649.1)
  finalLocalPosition: Offset(115.7, 16.3)
  button: 1
  sent tap down
================================================================================
```

**Comment by Rexios80** [comment]
It's not this package that would be out of date. It would be one of its dependencies.

**Comment by Rexios80** [comment]
If you're still having that problem, please create another issue for it

**Comment by Rexios80** [comment]
Added documentation to the readme on how to create a custom style

**Comment by Rexios80** [comment]
The issue you were having should have been fixed by this: https://github.com/firebase/FirebaseUI-Flutter/pull/107
